dataset_path: ../AllDatasets/
train_dataset_type: avenue
train_dataset_args: {augment: aug1, h: 256, w: 256, c: 3, t_length: 5, batch_size: 1, num_workers: 0}
test_dataset_type: avenue
test_dataset_args: {augment: aug1, h: 256, w: 256, c: 3, t_length: 5, batch_size: 1, num_workers: 0}

generator: cycle_generator_convlstm
flow_model: flownet2
model_args: {memory_size: 10, feature_dim: 512, key_dim: 512}

optimizer_G: Adam
optimizer_G_args: {lr: 0.0002, weight_decay: 0, lr_scheduler: None}

# loss cof
lam_object: 0
lam_int: 2.0
lam_gd: 2.0
# no flow loss
lam_op: 0  # 2.0

epochs: 100

save_epoch: 5
