dataset_path: ../AllDatasets/
train_dataset_type: ped2
train_dataset_args: {augment: aug1, h: 256, w: 256, c: 3, t_length: 5, batch_size: 4, num_workers: 0}
test_dataset_type: ped2
test_dataset_args: {augment: aug1, h: 256, w: 256, c: 3, t_length: 5, batch_size: 1, num_workers: 0}

model: nmad
model_args: {memory_size: 10, feature_dim: 512, key_dim: 512}

optimizer: Adam
optimizer_args: {lr: 0.0002, weight_decay: 0, lr_scheduler: CosineAnnealingLR, T_max: 60}

epochs: 60

save_epoch: 5
